# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\path\\to\\dir'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['_tkinter', '_ssl', 'PIL'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='main',
          debug=False,
          strip=False,
          upx=False,
          console=False )

a.binaries = a.binaries - TOC([
('mkl_p4m3.dll', None, None),
('mkl_avx512.dll', None, None),
('mkl_avx2.dll', None, None),
('mkl_p4m.dll', None, None),
#('mkl_p4.dll', None, None),
#('mkl_core.dll', None, None),
('mkl_vml_avx2.dll', None, None),
('mkl_vml_avx512.dll', None, None),
('mkl_vml_avx.dll', None, None),
#('mkl_intel_thread.dll', None, None),
('mkl_vml_p4m3.dll', None, None),
('mkl_rt.dll', None, None),
('mkl_vml_p4m2.dll', None, None),
('mkl_vml_p4m.dll', None, None),
('mkl_vml_p4.dll', None, None),
('mkl_avx.dll', None, None),
('mkl_vml_ia.dll', None, None),
('mkl_vml_cmpt.dll', None, None),
('mkl_tbb_thread.dll', None, None),
('mkl_sequential.dll', None, None),
('mkl_msg.dll', None, None),

('mfc90u.dll', None, None),
('mfc90.dll', None, None),
('_bsddb.pyd', None, None),
('QtXml4.dll', None, None),
('QtSvg4.dll', None, None),
('mfcm90u.dll', None, None),
('mfcm90.dll', None, None),
('bz2.pyd', None, None),
('matplotlib.backends._tkagg.pyd', None, None),
('qt4_plugins', None, None),
('pytz', None, None),
('msvcp90.dll', None, None),
('msvcr90.dll', None, None),
('QtOpenGL4.dll', None, None),
('QtXml4.dll', None, None),
('QtSvg4.dll', None, None),
('_hashlib.pyd', None, None),
('tcl', None, None),
('tk', None, None),
('sqlite3.dll', None, None),
('tcl85.dll', None, None),
('tk85.dll', None, None),
('_sqlite3', None, None),
('_ssl', None, None),
('_tkinter', None, None)])

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               name='main')
